name: env-name-here-does-not-matter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
## RNA assembly 
 - trinity
## Quality Control
  - Cutadapt
  - jellyfish
  - multiqc
  - fastqc=0.11.8
  - sortmerna=2.1b
  - trim-galore=0.6.4
